# This file is automatically generated from a slco file
# Necessary inputs:
import time

# Defining classes
# Class
class Calculator:
	port0 = in
	port1 = out

	def Main():


# Class
class User:
	port0 = in
	port1 = out

	def Loop():
		var0 = r

		var1 = r

class c0:
	def __init__(self):
		return

	# sync function between ports...
	def sync(self, u, c):
		 c.states["in"]= u.states["out"]
class c1:
	def __init__(self):
		return

	# sync function between ports...
	def sync(self, c, u):
		 u.states["in"]= c.states["out"]

# Initialize the classes
def makeModel():
	portsCalculator = ["in""out"]
	state_machinesCalculator = ["Main"]
	initial_statesCalculator = ["S"]

	portsUser = ["in""out"]
	state_machinesUser = ["Loop"]
	initial_statesUser = ["Start"]

	c = Calculator(portsCalculator, state_machinesCalculator, initial_statesCalculator)
	u = User(portsUser, state_machinesUser, initial_statesUser)

