<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="graph" nsURI="http://glt.tue.nl/graph" nsPrefix="graph">
  <eClassifiers xsi:type="ecore:EClass" name="Graph">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodes" upperBound="-1"
        eType="#//Node" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shape" lowerBound="1" eType="#//Shape"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outEdges" upperBound="-1"
        eType="#//Edge" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="style" lowerBound="1" eType="#//Style"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Node"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Shape">
    <eLiterals name="BOX"/>
    <eLiterals name="OVAL" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Style">
    <eLiterals name="SOLID"/>
    <eLiterals name="DOTTED" value="1"/>
    <eLiterals name="DASHED" value="2"/>
  </eClassifiers>
</ecore:EPackage>
